version: '3'
services:
  api:
    build:
      dockerfile: server.Dockerfile
      context: ./
    ports:
      - 3333:3333
  client:
    build:
      dockerfile: mytodos-app.Dockerfile
      context: ./
  nginx:
    restart: always
    build:
      dockerfile: nginx.Dockerfile
      context: ./nginx
    ports:
      - 80:80
