// user constants
export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL';
export const USER_LOGOUT = 'USER_LOGOUT';

export const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST';
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS';
export const USER_REGISTER_FAIL = 'USER_REGISTER_FAIL';
export const USER_REGISTER_RESET = 'USER_REGISTER_RESET';

//Todos constants
export const TODOS_LIST_REQUEST = 'TODOS_LIST_REQUEST';
export const TODOS_LIST_SUCCESS = 'TODOS_LIST_SUCCESS';
export const TODOS_LIST_FAIL = 'TODOS_LIST_FAIL';
export const TODOS_LIST_RESET = 'TODOS_LIST_RESET';

export const TODOS_UPDATE_REQUEST = 'TODOS_UPDATE_REQUEST';
export const TODOS_UPDATE_SUCCESS = 'TODOS_UPDATE_SUCCESS';
export const TODOS_UPDATE_FAIL = 'TODOS_UPDATE_FAIL';
export const TODOS_UPDATE_RESET = 'TODOS_UPDATE_RESET';

export const TODOS_REMOVE_ITEM_REQUEST = 'TODOS_REMOVE_ITEM_REQUEST';
export const TODOS_REMOVE_ITEM_SUCCESS = 'TODOS_REMOVE_ITEM_SUCCESS';
export const TODOS_REMOVE_ITEM_FAIL = 'TODOS_REMOVE_ITEM_FAIL';
