import {
  TODOS_LIST_FAIL,
  TODOS_LIST_REQUEST,
  TODOS_LIST_RESET,
  TODOS_LIST_SUCCESS,
  TODOS_UPDATE_FAIL,
  TODOS_UPDATE_REQUEST,
  TODOS_UPDATE_RESET,
  TODOS_UPDATE_SUCCESS,
  USER_LOGIN_FAIL,
  USER_LOGIN_REQUEST,
  USER_LOGIN_SUCCESS,
  USER_LOGOUT,
  USER_REGISTER_FAIL,
  USER_REGISTER_REQUEST,
  USER_REGISTER_RESET,
  USER_REGISTER_SUCCESS,
  TODOS_REMOVE_ITEM_REQUEST,
  TODOS_REMOVE_ITEM_FAIL,
  TODOS_REMOVE_ITEM_SUCCESS,
  TODOS_REMOVE_COMPLETED_ITEMS_REQUEST,
  TODOS_REMOVE_COMPLETED_ITEMS_FAIL,
  TODOS_REMOVE_COMPLETED_ITEMS_SUCCESS,
  TODOS_CREATE_FAIL,
  TODOS_CREATE_REQUEST,
  TODOS_CREATE_RESET,
  TODOS_CREATE_SUCCESS,
  TODOS_SEARCH_REQUEST,
  TODOS_SEARCH_FAIL,
  TODOS_SEARCH_SUCCESS,
  TODOS_SEARCH_RESET,
} from '../constants';
import { IUserInfo } from '../interfaces/payloadUser';

interface IUserTypes {
  type:
    | typeof USER_LOGIN_SUCCESS
    | typeof USER_LOGIN_FAIL
    | typeof USER_LOGIN_REQUEST
    | typeof USER_LOGOUT
    | typeof USER_REGISTER_SUCCESS
    | typeof USER_REGISTER_FAIL
    | typeof USER_REGISTER_REQUEST
    | typeof USER_REGISTER_RESET;

  payload: IUserInfo | string;
}

interface ITodosTypes {
  type:
    | typeof TODOS_LIST_SUCCESS
    | typeof TODOS_LIST_FAIL
    | typeof TODOS_LIST_REQUEST
    | typeof TODOS_LIST_RESET
    | typeof TODOS_UPDATE_REQUEST
    | typeof TODOS_UPDATE_SUCCESS
    | typeof TODOS_UPDATE_FAIL
    | typeof TODOS_UPDATE_RESET
    | typeof TODOS_REMOVE_ITEM_REQUEST
    | typeof TODOS_REMOVE_ITEM_FAIL
    | typeof TODOS_REMOVE_ITEM_SUCCESS
    | typeof TODOS_REMOVE_COMPLETED_ITEMS_REQUEST
    | typeof TODOS_REMOVE_COMPLETED_ITEMS_FAIL
    | typeof TODOS_REMOVE_COMPLETED_ITEMS_SUCCESS
    | typeof TODOS_CREATE_FAIL
    | typeof TODOS_CREATE_REQUEST
    | typeof TODOS_CREATE_RESET
    | typeof TODOS_CREATE_SUCCESS
    | typeof TODOS_SEARCH_REQUEST
    | typeof TODOS_SEARCH_FAIL
    | typeof TODOS_SEARCH_SUCCESS
    | typeof TODOS_SEARCH_RESET;
  payload: any;
}

export type UserTypes = IUserTypes;
export type TodosTypes = ITodosTypes;
